CREATE TABLE IF NOT EXISTS `lastmatch` ( `id` INT NOT NULL , `matchid` BIGINT NOT NULL , `name` VARCHAR(100) , PRIMARY KEY (`id`)) ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS `log` ( `id` INT NOT NULL AUTO_INCREMENT , `timestamp` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP , `message` TEXT NOT NULL , `error` BOOLEAN NOT NULL , PRIMARY KEY (`id`)) ENGINE = InnoDB;